common/models/AccountDetails.php
<?php

namespace common\models;

class AccountDetails extends \common\models\base\AccountDetailsBase
{
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->setAttribute('created_at', date('Y-m-d H:i:s'));
        }
        $this->setAttribute('updated_at', date('Y-m-d H:i:s'));

        return parent::beforeSave($insert);
    }
}

backend/controllers/AccountDetailsController.php
<?php

namespace backend\controllers;

use backend\components\AdminCoreController;
use common\models\AccountDetails;
use common\models\AccountDetailsSearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * AccountDetailsController implements the CRUD actions for AccountDetails model.
 */
class AccountDetailsController extends AdminCoreController
{
    /**
     * {@inheritdoc}
     */
    /*public function behaviors()
    {
    return [
    'verbs' => [
    'class' => VerbFilter::className(),
    'actions' => [
    'delete' => ['POST'],
    ],
    ],
    ];
    }
     */
    /**
     * Lists all AccountDetails models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AccountDetailsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AccountDetails model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AccountDetails model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AccountDetails();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $post = Yii::$app->request->post();
            $postData = $post['AccountDetails'];
            $model->restaurant_id = $_GET['rid'];
            // Generate Stripe Bank account and connect account from the data
            \Stripe\Stripe::setApiKey("sk_test_ZBaRU0wL5z8YaEEPUhY3jzgF00tdHXg5cp");
            try {
                // first create bank token
                $bankToken = \Stripe\Token::create([
                    'bank_account' => [
                        'country' => 'US',
                        'currency' => 'usd',
                        'account_holder_name' => $postData['stripe_bank_account_holder_name'],
                        'account_holder_type' => $postData['stripe_bank_account_holder_type'],
                        'routing_number' => $postData['stripe_bank_routing_number'],
                        'account_number' => $postData['stripe_bank_account_number'],
                    ],
                ]);

                $account_holder_name = explode(" ", $postData['stripe_bank_account_holder_name']);
                $first_name = $account_holder_name[0];
                $last_name = $account_holder_name[1];
                // second create stripe account
                $stripeAccount = \Stripe\Account::create([
                    "type" => "custom",
                    "country" => "US",
                    "email" => $postData['stripe_email'],
                    "business_type" => "individual",
                    "business_profile" => [
                        "url" => "http://www.zenocraft.com",
                    ],
                    "individual" => [
                        "first_name" => $first_name,
                        "last_name" => $last_name,
                    ],
                    "requested_capabilities" => ['transfers'],
                ]);

                // third link the bank account with the stripe account
                $bankAccount = \Stripe\Account::createExternalAccount(
                    $stripeAccount->id, ['external_account' => $bankToken->id]
                );
                // Fourth stripe account update for tos acceptance
                \Stripe\Account::update(
                    $stripeAccount->id, [
                        'tos_acceptance' => [
                            'date' => time(),
                            'ip' => $_SERVER['REMOTE_ADDR'], // Assumes you're not using a proxy
                        ],
                    ]
                );
                $response = ["bankToken" => $bankToken->id, "stripeAccount" => $stripeAccount->id, "bankAccount" => $bankAccount->id];
                $model->stripe_bank_token = $response['bankToken'];
                $model->stripe_connect_account_id = $response['stripeAccount'];
                $model->stripe_bank_accout_id = $response['bankAccount'];
                $model->save(false);
                Yii::$app->session->setFlash('success', Yii::getAlias('@account_details_add_message'));
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', "Something went wrong for creating stripe account please try again later");
            }
            return $this->redirect(['index', 'rid' => $model->restaurant_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing AccountDetails model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!empty(Yii::$app->request->post()) && $model->validate()) {
            $post = Yii::$app->request->post();
            $postData = $post['AccountDetails'];
            if (($model->stripe_email != $postData['stripe_email']) || ($model->stripe_bank_account_holder_name != $postData['stripe_bank_account_holder_name']) || ($model->stripe_bank_account_holder_type != $postData['stripe_bank_account_holder_type']) || ($model->stripe_bank_routing_number != $postData['stripe_bank_routing_number']) || ($model->stripe_bank_account_number != $postData['stripe_bank_account_number'])) {
                \Stripe\Stripe::setApiKey("sk_test_ZBaRU0wL5z8YaEEPUhY3jzgF00tdHXg5cp");
                try {
                    // first create bank token
                    $bankToken = \Stripe\Token::create([
                        'bank_account' => [
                            'country' => 'US',
                            'currency' => 'usd',
                            'account_holder_name' => $postData['stripe_bank_account_holder_name'],
                            'account_holder_type' => $postData['stripe_bank_account_holder_type'],
                            'routing_number' => $postData['stripe_bank_routing_number'],
                            'account_number' => $postData['stripe_bank_account_number'],
                        ],
                    ]);

                    $account_holder_name = explode(" ", $postData['stripe_bank_account_holder_name']);
                    $first_name = $account_holder_name[0];
                    $last_name = $account_holder_name[1];
                    // second create stripe account
                    $stripeAccount = \Stripe\Account::create([
                        "type" => "custom",
                        "country" => "US",
                        "email" => $postData['stripe_email'],
                        "business_type" => "individual",
                        "business_profile" => [
                            "url" => "http://www.zenocraft.com",
                        ],
                        "individual" => [
                            "first_name" => $first_name,
                            "last_name" => $last_name,
                        ],
                        "requested_capabilities" => ['transfers'],
                    ]);

                    // third link the bank account with the stripe account
                    $bankAccount = \Stripe\Account::createExternalAccount(
                        $stripeAccount->id, ['external_account' => $bankToken->id]
                    );
                    // Fourth stripe account update for tos acceptance
                    \Stripe\Account::update(
                        $stripeAccount->id, [
                            'tos_acceptance' => [
                                'date' => time(),
                                'ip' => $_SERVER['REMOTE_ADDR'], // Assumes you're not using a proxy
                            ],
                        ]
                    );
                    $response = ["bankToken" => $bankToken->id, "stripeAccount" => $stripeAccount->id, "bankAccount" => $bankAccount->id];
                    $model->stripe_bank_token = $response['bankToken'];
                    $model->stripe_connect_account_id = $response['stripeAccount'];
                    $model->stripe_bank_accout_id = $response['bankAccount'];
                    $model->restaurant_id = $_GET['rid'];
                    $model->paypal_email = $postData['paypal_email'];
                    $model->stripe_email = $postData['stripe_email'];
                    $model->stripe_bank_account_holder_name = $postData['stripe_bank_account_holder_name'];
                    $model->stripe_bank_account_holder_name = $postData['stripe_bank_account_holder_name'];
                    $model->stripe_bank_account_holder_type = $postData['stripe_bank_account_holder_type'];
                    $model->stripe_bank_routing_number = $postData['stripe_bank_routing_number'];
                    $model->stripe_bank_account_number = $postData['stripe_bank_account_number'];
                    $model->save(false);
                    Yii::$app->session->setFlash('success', Yii::getAlias('@account_details_update_message'));
                    return $this->redirect(['index', 'rid' => $model->restaurant_id]);
                } catch (\Exception $e) {
                    Yii::$app->session->setFlash('error', "Something went wrong for creating stripe account please try again later");
                    return $this->redirect(['index', 'rid' => $model->restaurant_id]);
                }
            } else {

backend/views/account-details/_form.php
<?php

use common\components\Common;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\AccountDetails */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
    </div>
    <div class="block-content collapse in">
<div class="account-details-form span12 common_search">

    <?php $form = ActiveForm::begin();?>

     <div class="row">
    <div class="span3">
    <?=$form->field($model, 'restaurant_id')->textInput(["value" => Common::get_name_by_id($_GET['rid'], "Restaurants"), 'disabled' => 'true'])?>
</div>
</div>
 <div class="row">
    <div class="span3">
    <?=$form->field($model, 'paypal_email')->textInput(['maxlength' => true])?>
</div>
</div>
<div class="row">
    <div class="span3">
    <?=$form->field($model, 'stripe_email')->textInput(['maxlength' => true])?>
</div>
</div>
 <div class="row">
    <div class="span3">
    <?=$form->field($model, 'stripe_bank_account_holder_name')->textInput(['maxlength' => true])?>
    </div>
</div>
 <div class="row">
    <div class="span3">
    <?=$form->field($model, 'stripe_bank_account_holder_type')->textInput(['maxlength' => true])?>
    </div>
</div>
 <div class="row">
    <div class="span3">
    <?=$form->field($model, 'stripe_bank_routing_number')->textInput()?>
    </div>
</div>
 <div class="row">
    <div class="span3">
    <?=$form->field($model, 'stripe_bank_account_number')->textInput()?>
    </div>
</div>
    <div class="form-group">
        <?=Html::submitButton('Save', ['class' => 'btn btn-success'])?>
    </div>

    <?php ActiveForm::end();?>
</div>
    </div>
</div>

backend/views/account-details/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\AccountDetailsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="account-details-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'restaurant_id') ?>

    <?= $form->field($model, 'paypal_email') ?>

    <?= $form->field($model, 'stripe_bank_account_holder_name') ?>

    <?= $form->field($model, 'stripe_bank_account_holder_type') ?>

    <?php // echo $form->field($model, 'stripe_bank_routing_number') ?>

    <?php // echo $form->field($model, 'stripe_bank_account_number') ?>

    <?php // echo $form->field($model, 'stripe_bank_token') ?>

    <?php // echo $form->field($model, 'stripe_connect_account_id') ?>

    <?php // echo $form->field($model, 'stripe_bank_accout_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/account-details/create.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\AccountDetails */

$this->title = 'Create Account Details';
$this->params['breadcrumbs'][] = ['label' => 'Manage Restaurants', 'url' => ['restaurants/index']];
$this->params['breadcrumbs'][] = ['label' => 'Account Details', 'url' => ['index'], 'rid' => $_GET['rid']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="account-details-create email-format-create">

    <?=$this->render('_form', [
    'model' => $model,
])?>

</div>

backend/views/account-details/index.php
<?php

use common\components\Common;
use common\models\AccountDetails;
use yii\grid\GridView;
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $searchModel common\models\AccountDetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Account Details';
$this->params['breadcrumbs'][] = ['label' => 'Manage Restaurants', 'url' => ['restaurants/index']];
$this->params['breadcrumbs'][] = ['label' => Common::get_name_by_id($_GET['rid'], "Restaurants")];
$this->params['breadcrumbs'][] = $this->title;
?>

<style type="text/css">
    
.nav-list li:nth-child(4), .nav-list li:nth-child(4) a:hover{background: #006dcc;}
.nav-list li:nth-child(4) span, .nav-list li:nth-child(4) span:hover{color: #fff!important;}

</style>
<div class="account-details-index email-format-index">
     <div class="email-format-index">

</div>
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
        <div class="pull-right">
            <?php
$accountDetails = AccountDetails::find()->where(['restaurant_id' => $_GET['rid']])->one();
if (empty($accountDetails)) {?>

            <?=Html::a(Yii::t('app', '<i class="icon-plus"></i> Add Account Details'), ['create', 'rid' => $_GET['rid']], ['class' => 'btn btn-success'])?>
        <?php }?>
            <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> Reset'), Yii::$app->urlManager->createUrl(['account-details/index']), ['class' => 'btn btn-primary'])?>
        </div>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]);  ?>
    <div class="block-content">
        <div class="goodtable">


    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?=GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        //'id',
        [
            'attribute' => 'restaurant_id',
            'filterOptions' => ["style" => "width:13%;"],
            'headerOptions' => ["style" => "width:13%;"],
            'contentOptions' => ["style" => "width:13%;"],
            'value' => function ($data) {
                return !empty($data->restaurant_id) ? $data->restaurant->name : "";
            },
        ],
        'paypal_email:email',
        'stripe_bank_account_holder_name',
        'stripe_bank_account_holder_type',
        //'stripe_bank_routing_number',
        //'stripe_bank_account_number',
        //'stripe_bank_token',
        //'stripe_connect_account_id',
        //'stripe_bank_accout_id',
        //'created_at',
        //'updated_at',

        [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{update}',
            'buttons' => [
                'update' => function ($url, $model) {
                    $flag = 1;
                    $url = Yii::$app->urlManager->createUrl(['account-details/update', "rid" => $_GET['rid'], 'id' => $model->id]);
                    return Common::template_update_button($url, $model, $flag);
                },

            ],
        ],
    ],
]);?>
        </div>
    </div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">
$( document ).ready(function() {
    $('.account-details-serach').hide();
        $('.open_search').click(function(){
            $('.account-details-serach').toggle();
        });
    });

</script>

backend/views/account-details/update.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\AccountDetails */

$this->title = 'Update Account Details: ' . $model->restaurant->name;
$this->params['breadcrumbs'][] = ['label' => 'Manage Restaurants', 'url' => ['restaurants/index']];
$this->params['breadcrumbs'][] = ['label' => 'Account Details', 'url' => ['index'], 'rid' => $model->restaurant_id];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<style type="text/css">
    
.nav-list li:nth-child(4), .nav-list li:nth-child(4) a:hover{background: #006dcc;}
.nav-list li:nth-child(4) span, .nav-list li:nth-child(4) span:hover{color: #fff!important;}

</style>

<div class="account-details-update email-format-create">

    <?=$this->render('_form', [
    'model' => $model,
])?>

</div>

backend/views/account-details/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\AccountDetails */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Account Details', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="account-details-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'restaurant_id',
            'paypal_email:email',
            'stripe_bank_account_holder_name',
            'stripe_bank_account_holder_type',
            'stripe_bank_routing_number',
            'stripe_bank_account_number',
            'stripe_bank_token',
            'stripe_connect_account_id',
            'stripe_bank_accout_id',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>